package tech.unispace.pillreminder.ui

/**
 * История версий. Показывается по нажатию на строку версии внизу настроек —
 * специально без отдельного пункта меню, чтобы не занимать место.
 *
 * Новая версия = запись сверху. Дата пустая, пока версия не выпущена.
 */
data class ReleaseNotes(
    val version: String,
    /** Дата выпуска в формате «30.08.2026»; пусто — ещё не выпущено. */
    val date: String,
    val ru: List<String>,
    val en: List<String>,
)

val CHANGELOG: List<ReleaseNotes> = listOf(
    ReleaseNotes(
        version = "1.2.4",
        date = "16.09.2026",
        ru = listOf(
            "Отчёт для врача: таблетки можно отмечать галочками — то, что к этому врачу не относится, не попадёт ни в списки, ни в процент дисциплины.",
            "Набор таблеток сохраняется как пресет врача («Кардиолог», «Эндокринолог») и выбирается одним нажатием; рядом короткая подсказка, как это работает.",
            "Мастер: форма выпуска — выпадающим списком; поле дозировки во всю ширину, без единицы справа.",
            "Бегущая строка осталась только у названий таблеток — на кнопках-пресетах текст больше не крутится.",
        ),
        en = listOf(
            "Doctor report: pick the pills with checkboxes — anything unrelated to this doctor stays out of the lists and of the adherence percentage.",
            "A selection can be saved as a doctor preset (\"Cardiologist\", \"Endocrinologist\") and applied with one tap; a short guide explains it in place.",
            "Wizard: the dosage form is a dropdown; the strength field spans the full width, with no unit label beside it.",
            "The marquee is now limited to pill names — preset buttons no longer scroll their text.",
        ),
    ),
    ReleaseNotes(
        version = "1.2.3",
        date = "15.09.2026",
        ru = listOf(
            "Календарь истории: цвет дня — ступени от красного к зелёному через жёлтый по 20 % выпитого; цифра на цветной клетке всегда белая.",
            "Журнал: правка прошлого дня — только через кнопку «Изменить историю» с подтверждением.",
            "Журнал: недельная лента не сжимает воскресенье, кнопки приёма — под текстом, подпись вкладки «Настройки» не обрезается.",
            "Фраза «Сегодня отличный день, чтобы начать серию» показывается только на сегодняшнем дне.",
            "Календарь: легенда маркерами, «сегодня» — рамкой поверх реального цвета дня, будущие дни полупрозрачные, под числом — точки приёмов, под календарём — превью выбранного дня с кнопкой «В журнал».",
            "Мастер: приём по дням недели («пн, ср, пт», «по будням»); частота — «каждый день · через день · по дням недели · свой интервал»; поля «другое…» открываются только по запросу; чипы сеткой; итог шага — «Каждый день, 3 раза в день (курс: бессрочно)».",
            "Мастер стал трёхшаговым: «Что пьём» · «Как и сколько принимать» · «Курс и контроль». Связь с едой — один селектор «Неважно · До еды · Во время · После еды». Пустая дозировка больше не даёт «мг × 1 таб.».",
            "Мастер: вместо списков «Итог» и «Что будет на карточке» — карточка таблетки в миниатюре, как на главном; тап по карточке или метке ведёт к нужному полю. Отсчёт от подъёма и разнос с другими таблетками — за спойлером «Дополнительные параметры расписания». Чипы не обрезаются, поля чисел скрыты до нажатия «другое…»; тап по метке превью прокручивает к нужному блоку. «По часам» начинается с одного времени 09:00.",
            "Настройки: тумблер «Во весь экран» сам открывает системное разрешение и включается только после него; порог «таблетки заканчиваются» — степпер с вводом числа и чипы «+3 … +20»; тумблер «Во весь экран» без разрешения выключается сам; у встроенных сроков напоминаний о врачах нет крестика; поле «свой интервал» повторов скрыто за чипом; контент не заезжает под строку состояния.",
            "Отчёт: в TXT, PDF и «Поделиться» разделы без данных не печатаются; в предпросмотре остаются как «нет данных».",
            "Календарь: превью выбранного дня — такая же схема дня, как на главном; для будущих дней без событий блока нет. Схема дня на главном появляется сразу после «Подъёма», без пролага.",
            "Поиск по заметкам: по названию, описанию, тексту и тегам, без учёта регистра и «ё/е», по всем словам запроса.",
            "Длинные названия таблеток едут каруселью, а не режутся многоточием — на карточках, в журнале, каталоге и чипах мастера.",
            "Мастер: «Первый приём» и «Разносить с другими» — ровными сетками; блок, к которому привёл тап по метке превью, подсвечивается. Если такая таблетка уже в расписании — предупреждение, но добавить можно.",
            "Мастер: форма выпуска и единицы дозировки — тоже сеткой; ряды пресетов ближе друг к другу; переходы «превью → блок» без лагов. Меню долгого нажатия на карточке — с вопросом и кнопкой «Изменить», а не пустое.",
        ),
        en = listOf(
            "History calendar: day color steps from red to green through yellow by 20 % taken; the number on a colored cell is always white.",
            "Journal: editing a past day only via the \"Edit history\" button with confirmation.",
            "Journal: the week strip no longer squeezes Sunday, intake buttons sit under the text, the \"Settings\" tab label is not cut off.",
            "The \"Today is a great day to start a streak\" line is shown only on today.",
            "Calendar: legend as markers, today is a border over the day's real color, future days are translucent, intake dots under the number, and a preview of the selected day with an \"Open journal\" button below the calendar.",
            "Wizard: intake on days of the week (\"Mon, Wed, Fri\", \"on weekdays\"); frequency — \"every day · every other day · days of the week · custom interval\"; \"other…\" fields open only on demand; chips in a grid; step summary — \"Every day, 3 times a day (course: unlimited)\".",
            "The wizard is now three steps: \"What you take\" · \"How and how much\" · \"Course and control\". Relation to food is one selector \"Any time · Before meal · With meal · After meal\". An empty strength no longer yields \"mg × 1 tab.\".",
            "Wizard: the \"Summary\" and \"What the card will show\" lists are replaced by a miniature pill card as on the home screen; tapping the card or a label jumps to the field. Offset from waking and spacing from other pills sit behind \"Advanced schedule options\". Chips no longer truncate, number fields stay hidden until \"other…\"; tapping a preview label scrolls to the block. \"By clock\" starts with a single 09:00.",
            "Settings: the \"Full screen\" switch opens the system permission itself and turns on only after it is granted; the low-stock threshold is a stepper with a typed number and \"+3 … +20\" chips; the \"Full screen\" switch turns itself off without the permission; built-in visit lead times have no delete cross; the custom repeat interval field hides behind a chip; content no longer slides under the status bar.",
            "Report: TXT, PDF and Share omit sections without data; the preview still shows them as \"no data\".",
            "Calendar: the selected-day preview is the same day timeline as on the home screen; future days without events show no block. The home timeline appears right after \"Woke up\", without a lag.",
            "Notes search: title, description, body and tags, case-insensitive, \"ё/е\"-insensitive, all query words must match.",
            "Long pill names scroll like a marquee instead of being cut with an ellipsis — on cards, in the journal, the catalog and wizard chips.",
            "Wizard: \"First intake\" and \"Keep apart\" are neat grids; the block a preview label scrolls to is highlighted. A pill already on the schedule triggers a warning but can still be added.",
            "Wizard: form and dose units are grids too; preset rows sit closer together; \"preview → block\" jumps no longer lag. The long-press menu on a card has a prompt and an \"Edit\" button instead of an empty body.",
        ),
    ),
    ReleaseNotes(
        version = "1.2.2",
        date = "14.09.2026",
        ru = listOf(
            "Всё, чему пора, — одним уведомлением: приёмы с разным плановым временем больше не звонят параллельными цепочками каждые три минуты.",
            "Первые пять минут после планового времени карточка пишет «сейчас», а не «опоздание на 2 мин».",
            "Трекеры на одно время — одно уведомление «Пора записать: вес, настроение, сон» в отдельном канале обычной важности, без плашки поверх напоминания о таблетке.",
        ),
        en = listOf(
            "Everything that is due comes as one notification: intakes with different planned times no longer ring in parallel chains every three minutes.",
            "For the first five minutes after the planned time the card says \"now\" instead of \"2 min late\".",
            "Trackers set to the same time come as one notification \"Time to record: weight, mood, sleep\" in a separate normal-importance channel, without a heads-up banner over the pill reminder.",
        ),
    ),
    ReleaseNotes(
        version = "1.2.1",
        date = "13.09.2026",
        ru = listOf(
            "Забыли нажать «Еда»: в расчётное время приходит мягкое напоминание «Поели?» с кнопками «Еда» и «Выпито».",
            "«Отложить» прямо на карточке таблетки; прогресс набора — точками вместо «Приём 1 из 3».",
            "Красный цвет — только при опоздании больше 2 часов; до этого приём «ждёт» янтарным. Сегодняшний день в календаре не краснеет, пока не закончился.",
            "Схема дня — отдельной карточкой, короткие подписи («Эсц 10мг»), тап по кружку подсвечивает карточку.",
            "Метки без дублей: «10 мг × 2 таб.», калории внутри правила «после еды»; комментарий — строкой, а не кнопкой.",
            "Кнопки «Отчёт · Советы · Туториал» — внизу главного экрана. Порядок таблеток — через долгое нажатие, без перетаскивания.",
            "Заметка — один экран. Визит: адрес или кабинет, переключатель напоминания и точные моменты уведомлений.",
            "Экран «Виджет» в настройках: палитра цветов, подписи «Светлые/Тёмные обои», реальные приёмы в предпросмотре.",
            "Мастер: итог шага «Как часто» — последним и с курсом. Каталог: «зачем фото» под кнопкой. Трекеры: без «Создать все три», сетка мини-графика видна.",
        ),
        en = listOf(
            "Forgot to tap \"Ate\": at the planned time a gentle \"Had a meal?\" nudge arrives with \"Ate\" and \"Taken\" buttons.",
            "Snooze right on the pill card; set progress as dots instead of \"Intake 1 of 3\".",
            "Red only when more than 2 hours late; before that the intake \"waits\" in amber. Today never turns red in the calendar until the day is over.",
            "Day timeline as its own card, short labels (\"Esc 10mg\"), tapping a circle highlights the card.",
            "No duplicate labels: \"10 mg × 2 tab.\", calories inside the \"after a meal\" rule; the comment is a line, not a button.",
            "\"Report · Tips · Tutorial\" moved to the bottom of the home screen. Pill order via long press, no dragging.",
            "Note is a single screen. Visit: address or room, a reminder switch and the exact reminder moments.",
            "\"Widget\" screen in Settings: color palette, \"Light/Dark wallpaper\" labels, real intakes in the preview.",
            "Wizard: the \"How often\" summary comes last and includes the course. Catalog: \"why a photo\" under the button. Trackers: no \"Create all three\", the mini chart grid is visible.",
        ),
    ),
    ReleaseNotes(
        version = "1.2",
        date = "13.09.2026",
        ru = listOf(
            "Приём «после еды» ждёт кнопку «Еда»: до еды будильник не звонит, карточка показывает «ждёт „Еда“», после — напоминает через выбранное время. Страховка — напоминание через 3 часа.",
            "Связь с едой видна на карточке, в итоге мастера, в шторке и на виджете; «сразу после еды» — словами, а не «1 мин».",
            "Схема дня в карточке пробуждения: подъём → таблетки → еда → сон с промежутками между ними; выключается в «Внешнем виде».",
            "Первый приём: пресеты «Днём (+6 ч)» и «Вечером (+12 ч)», смещение в часах и минутах.",
            "Необязательная пометка «минимум калорий» в связи с едой — видна на карточке, в шторке и на виджете.",
            "Карточка: название своей строкой, время крупнее; «Всё выпито · 1 из 1» вместо «0 из 1».",
            "Мастер: «Через промежуток / По часам» вместо двойного «От пробуждения», стрелка вместо «Назад», кнопки внизу помещаются.",
            "Виджет: дозировка в строке приёма, условия приёма под каждой таблеткой (в широком — и комментарий); цвет, прозрачность и цвет текста настраиваются.",
            "Ревью: «Отложить» и повторы не сбиваются действиями в приложении; «Сон» снимает оставшиеся приёмы дня; удаление таблетки отвязывает связанные; бэкап хранит привязку заметок и восстанавливается одной транзакцией.",
            "Ревью: отчёт и серия «без пропусков» не считают будущие приёмы пропусками; «Принять все» и «Пропустить все» для группы; подтверждения удаления везде; приёмы прошлых дней отмечаются из журнала; ошибочную «Еду» можно убрать долгим нажатием.",
        ),
        en = listOf(
            "An \"after a meal\" intake waits for the \"Ate\" button: no alarm before the meal, the card says \"waits for Ate\", then it reminds after the chosen delay. Safety net: a reminder 3 hours later.",
            "Food relation is shown on the card, in the wizard summary, in the shade and on the widget; \"right after a meal\" in words, not \"1 min\".",
            "Day timeline in the wake-up card: wake-up → pills → meals → bed with the gaps between them; can be turned off in \"Appearance\".",
            "First intake: \"Afternoon (+6 h)\" and \"Evening (+12 h)\" presets, offset in hours and minutes.",
            "Optional \"minimum meal calories\" note in the food relation — shown on the card, in the shade and on the widget.",
            "Card: the name on its own line, larger time; \"All done · 1 of 1\" instead of \"0 of 1\".",
            "Wizard: \"By interval / By clock\" instead of a doubled \"From wake-up\", an arrow instead of \"Back\", bottom buttons fit.",
            "Widget: dosage in the intake line, intake conditions under each pill (the wide one also shows the comment); background color, transparency and text color are adjustable.",
            "Review: snooze and repeats survive any action in the app; \"Sleep\" removes the day's remaining intakes; deleting a pill unlinks the linked ones; backup keeps note-to-pill links and restores in one transaction.",
            "Review: the report and the streak no longer count future intakes as missed; \"Take all\" and \"Skip all\" for a group; delete confirmations everywhere; past days' intakes can be marked from the journal; a mistaken \"Ate\" can be removed with a long press.",
        ),
    ),
    ReleaseNotes(
        version = "1.1",
        date = "03.09.2026",
        ru = listOf(
            "Расписание «по часам»: приёмы больше не ждут кнопку «Я проснулся».",
            "Кнопки «Сон» и «Еда»: сон сам попадает в трекер, а еда двигает приёмы, которые нельзя пить сразу после неё.",
            "Связь с едой у таблетки: «через N после еды» и «за N до еды», разнос с конкретными таблетками.",
            "Уведомления о приёмах в одну минуту объединяются, есть кнопка «Принять все».",
            "Полноэкранное напоминание: несколько кнопок «Отложить», выделенная кнопка «Пропустить».",
            "Быстрое сохранение таблетки после ввода названия и дублирование схемы.",
            "Трекер сна: отдельные оценки сна и пробуждения, совет по времени отбоя, автозаписи по кнопкам.",
            "Запись веса и настроения в один тап с главной.",
            "Поиск и теги в заметках, привязка заметки к таблетке, поиск по каталогу.",
            "Серия дней без пропусков и дисциплина по каждой таблетке.",
            "Прогноз «на сколько хватит упаковки» и два виджета: компактный и с кнопкой «Выпито».",
            "Вход по отпечатку или коду устройства.",
            "Пересчёт расписания при смене часового пояса.",
            "День длится максимум 18 часов и закрывается кнопкой «Сон».",
            "Еда и сон видны в истории дня; тепловая карта различает пропуски оранжевым.",
            "Сглаженные графики с фиксированной шкалой и настройкой вида.",
            "Мини-календарь визитов, связи между показателями в отчёте врача.",
            "Журнал дня — единая лента событий с фильтрами.",
            "Предупреждение при слишком коротком сне и перенос ночей из истории в трекер.",
            "Правила приоритета: сдвиги считаются от исходного времени и ограничены.",
            "Формулировки без рода: «Подъём», «Выпито», «Приём пищи».",
        ),
        en = listOf(
            "Clock-based schedule: intakes no longer wait for the \"I woke up\" button.",
            "\"Sleep\" and \"Ate\" buttons: sleep lands in the tracker by itself, meals push intakes that must not follow food.",
            "Food relation per pill: \"N after a meal\" and \"N before a meal\", plus keeping apart from chosen pills.",
            "Intakes due in the same minute are merged into one notification with \"Take all\".",
            "Full-screen reminder: several snooze buttons, a highlighted \"Skip\".",
            "Quick save of a pill right after the name and schedule duplication.",
            "Sleep tracker: separate sleep and wake-up ratings, bedtime advice, entries collected by buttons.",
            "One-tap weight and mood entries from the home screen.",
            "Search and tags in notes, linking a note to a pill, catalog search.",
            "Streak of days without misses and adherence per pill.",
            "\"Package lasts until\" forecast and two widgets: compact and with a \"Taken\" button.",
            "Unlock with fingerprint or device PIN.",
            "Schedule recalculation after a time zone change.",
            "The day lasts at most 18 hours and closes with the \"Sleep\" button.",
            "Meals and sleep show up in the day history; the heatmap marks misses in orange.",
            "Smooth charts with a fixed scale and a style setting.",
            "A mini calendar of visits and metric links in the doctor report.",
            "The day journal is a single timeline of events with filters.",
            "A warning about too little sleep and import of nights from history into the tracker.",
            "Priority rules: shifts are counted from the original time and are capped.",
            "Gender-neutral wording throughout the interface.",
        ),
    ),
    ReleaseNotes(
        version = "1.0",
        date = "30.08.2026",
        ru = listOf(
            "Первая версия: расписание от кнопки «Я проснулся», следующий приём — от фактического «Выпил».",
            "Мастер добавления таблетки: форма, дозировка, количество, курс, промежуток, связанные таблетки, приём по необходимости.",
            "Напоминания с повторами, «Отложить», тихими часами, звуком будильника и полноэкранным режимом.",
            "Заметки, визиты к врачу с напоминаниями, каталог лекарств с фото.",
            "Трекеры веса с ИМТ, настроения и сна: графики, статистика, корреляции.",
            "История: журнал по дням, тепловая карта, отчёт для врача (TXT и PDF), бэкап в файл.",
            "Виджет на рабочий стол, русский и английский язык, светлая и тёмная темы.",
        ),
        en = listOf(
            "First release: the schedule starts from the \"I woke up\" button, the next intake counts from the actual \"Taken\".",
            "Pill wizard: form, dosage, amount, course, gap, linked pills, as-needed intake.",
            "Reminders with repeats, snooze, quiet hours, alarm sound and full-screen mode.",
            "Notes, doctor visits with reminders, medication catalog with photos.",
            "Weight (with BMI), mood and sleep trackers: charts, stats, correlations.",
            "History: day journal, heatmap, doctor's report (TXT and PDF), backup to a file.",
            "Home-screen widget, Russian and English, light and dark themes.",
        ),
    ),
)
